spring:
  datasource:
    url: jdbc:mysql://192.168.0.29:3306/world?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10           #최대 pool size (defailt 10)
      connection-timeout: 5000
      connection-init-sql: SELECT 1   #SELECT 1
      validation-timeout: 2000        #2000
      minimum-idle: 10                #연결 풀에서 HikariCP가 유지 관리하는 최소 유휴 연결 수
      idle-timeout: 600000            #연결을위한 최대 유휴 시간
      max-lifetime: 1800000           #닫힌 후 pool 에있는 connection의 최대 수명 (ms)입니다.
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect